european_countries = {
    'Albánia': 'Tirana',
    'Andorra': 'Andorra la Vella',
    'Örményország': 'Jereván',
    'Ausztria': 'Bécs',
    'Azerbajdzsán': 'Baku',
    'Fehéroroszország': 'Minszk',
    'Belgium': 'Brüsszel',
    'Bosznia-Hercegovina': 'Szarajevó',
    'Bulgária': 'Sofia',
    'Horvátország': 'Zágráb',
    'Ciprus': 'Nicosia',
    'Csehország': 'Prága',
    'Dánia': 'Koppenhága',
    'Észtország': 'Tallinn',
    'Finnország': 'Helsinki',
    'Franciaország': 'Párizs',
    'Grúzia': 'Tbiliszi',
    'Németország': 'Berlin',
    'Görögország': 'Athén',
    'Magyarország': 'Budapest',
    'Izland': 'Reykjavík',
    'Írország': 'Dublin',
    'Olaszország': 'Róma',
    'Kazahsztán': 'Nurszultan',
    'Koszovó': 'Pristina',
    'Lettország': 'Riga',
    'Liechtenstein': 'Vaduz',
    'Litvánia': 'Vilnius',
    'Luxemburg': 'Luxemburg',
    'Málta': 'Valletta',
    'Moldova': 'Kisinyov',
    'Monaco': 'Monaco',
    'Montenegró': 'Podgorica',
    'Hollandia': 'Amszterdam',
    'Észak-Macedónia': 'Szkopje',
    'Norvégia': 'Oslo',
    'Lengyelország': 'Varsó',
    'Portugália': 'Lisszabon',
    'Románia': 'Bukarest',
    'Oroszország': 'Moszkva',
    'San Marino': 'San Marino',
    'Szerbia': 'Belgrád',
    'Szlovákia': 'Pozsony',
    'Szlovénia': 'Ljubljana',
    'Spanyolország': 'Madrid',
    'Svédország': 'Stockholm',
    'Svájc': 'Bern',
    'Törökország': 'Ankara',
    'Ukrajna': 'Kijev',
    'Egyesült Királyság': 'London',
    'Vatikánváros': 'Vatikánváros'
}